# Generated by Django 3.1.14 on 2023-05-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20230531_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='previous_evolutions',
        ),
    ]
